---
title: "MGMT-3453-X20: Homework 8-9"
author: "Bill Ash (5555WRA)"
date: "04/20/2021"
output:
  html_document: default
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,   
  fig.align = 'center'
)
library(tidyverse)
theme_set(theme_light())
```

# Problem 8 

```{r}
tribble(
  ~"act", ~"NODES",~"a",~"m",~"b",
  
  "A", "1-2", "2", "3", "4",
  "B", "2-3", "1", "2", "3",
  "C", "2-4", "4", "5", "12", 
  "D", "2-5", "3", "4", "11", 
  "E", "3-6", "1", "3", "5", 
  "F", "4-6", "1", "2", "3", 
  "G", "5-8", "1", "8", "9", 
  "H", "6-7", "2", "4", "6", 
  "I", "7-9", "2", "4", "12", 
  "J", "8-9", "3", "4", "5", 
  "K", "9-10", "5", "7", "8"
) %>% 
  mutate_at(c('a', 'm', 'b'), readr::parse_number) %>% 
  left_join(
    tibble::tribble(
      ~'NODES', ~'te', ~'EF', ~'LF', ~'SLACK', ~'CP',
      '1-2',      3,       3,  3,    0,    '*',
      '2-3',      2,       5,  8,    3,    NA,
      '2-4',      6,       9,  9,    0,    '*',
      '2-5',      5,       8,  9,    1,    NA, 
      '3-6',       3,      8,  11,   3,    NA,
      '4-6',      2,       11, 11,   0,    '*',
      '5-8',      7,       15, 16,   1,    NA,
      '6-7',      4,       15, 15,   0,    '*',
      '7-9',      5,       20, 20,   0,    '*',
      '8-9',      4,       19, 20,   1,   NA,
      '9-10', 6.83, 26.83, 26.83, 0,      '*'
    )
  ) %>% 
  knitr::kable()
```


Critical Path: 
1-2 >> 2-4 >> 4-6 >> 6-7 >> 7-9 >> 9-10

Expected Completion: 
26.83


# Problem 9 


```{r}
library(visNetwork)

list(
  nodes = tibble(
    id = 1:9, 
    label = id,
    shape = 'ellipse'
  ), 
  edges = dplyr::bind_rows(
    tribble(
~"act", ~"from",~'to', ~"label",
  "A","1","2","15",
  "B","2","3","12",
  "C","3","4","6",
  "D","3","9","5",
  "E","4","9","3",
  "F","1","5","8",
  "G","5","7","8",
  "H","5","6","9"), 
    tribble(
      ~"act", ~"from",~'to', ~"label",
      'I(dummy)', '6', '7', '0',
      'J(was I)', '7', '8', '14',
      'K(was J)', '7', '9', '7',
      'L(was K)', '8', '9', '8'
    )
  )
) %>% 
  {
    visNetwork(
      nodes = .[[1]], edges =  .[[2]], 
      main = 'PERT')
  } %>% 
  visEdges(
    arrows =list(to = list(enabled = TRUE, scaleFactor = 1)),
    color = list(color = "lightblue", highlight = "red"))
```

Expected Completion: 
39

Critical Path: 
1-5 >> 5-6 >> 6-7 >> 7-8 >> 8-9


